- name: Change ownership of the Django project directory
  become: yes
  ansible.builtin.file:
    path: /opt/sample-django
    owner: ec2-user
    group: ec2-user
    recurse: yes

- name: Deploy Gunicorn service configuration
  ansible.builtin.template:
    src: roles/deploy/templates/gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service

- name: Run systemctl daemon-reexec
  become: yes
  ansible.builtin.command: systemctl daemon-reexec

- name: Reload systemd manager configuration
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable gunicorn service
  become: yes
  ansible.builtin.systemd:
    name: gunicorn
    enabled: yes

- name: Start gunicorn service
  become: yes
  ansible.builtin.systemd:
    name: gunicorn
    state: started

